name: fordev_tdd
description: Enquetes para programadores.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  test:
  mocktail:
  faker:

flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/
